### ISSUE TITLE
CARA RUN DI VPS?

### ISSUE THREAD

**Issue by Finsiii** [hasyim404/WA-Intip#1]
CARA RUN DI VPS GMN BANG

**Comment by muhismail015** [comment]
1. Update
```
sudo apt-get update
```

2. Install NodeJS (v.20)
```
sudo apt-get install curl
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs
npm -v && node -v
```

3. Install Chromium-Browser
```
sudo apt install chromium-browser
```

6. Install PM2
```
sudo npm install pm2@latest -g
```

7. Install Package for Puppeteer
```
sudo apt-get install libatk1.0-0 libatk-bridge2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libnss3
```

8. clonning the repo and "npm install"

9. start bot
```
pm2 start index.js
```

10. scann barcode in app.log
```
cat app.log
```

**Comment by Finsiii** [comment]
> 1. Update
> 
> 
> ```
> sudo apt-get update
> ```
> 
>     2. Install NodeJS (v.20)
> 
> 
> ```
> sudo apt-get install curl
> curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
> sudo apt-get install nodejs
> npm -v && node -v
> ```
> 
>     3. Install Chromium-Browser
> 
> 
> ```
> sudo apt install chromium-browser
> ```
> 
>     6. Install PM2
> 
> 
> ```
> sudo npm install pm2@latest -g
> ```
> 
>     7. Install Package for Puppeteer
> 
> 
> ```
> sudo apt-get install libatk1.0-0 libatk-bridge2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libnss3
> ```
> 
>     8. clonning the repo and "npm install"
> 
>     9. start bot
> 
> 
> ```
> pm2 start index.js
> ```
> 
>     10. scann barcode in app.log
> 
> 
> ```
> cat app.log
> ```

okkay, i'll try soon
